[package]
name = "tab-memory-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
astra = "0.4.0"
dirs = "5.0.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sysinfo = "0.33.0"
thousands = "0.2.0"
toml = "0.8.19"
ws = "0.9.2"
