# Kill the most memory consuming tab in the background with the given strategy
# Options: rss_limit, idle_time_limit, memory_change_rate
kill_tab_strategies = ["rss_limit"]

# Check interval of choosen strategy
# Range: 0.0 ~ inf
check_interval_secs = 1.0

# A list of regex, tab will not be kill if matche any
# Example: whitelist: ["https://docs.rs"]
whitelist = []

# Kill the tab if all tabs total resident set size (physical memory usage) hit limit
[strategy.rss_limit]
# Range: 0 ~ 18_446_744_073_709_551_615
max_bytes = 2_000_000_000

# Kill the tab if idle time is too long, this will not kill "New Tab"
[strategy.idle_time_limit]
# Range: 0.0 ~ inf
max_secs = 86400.0

# Kill the tab if memory change rate is too low (meas it's may not being used)
# 🚧 Not implemented
[strategy.memory_change_rate]
# Range: 0.0 ~ 1.0
min_rate = 0.5
