# Kill the most memory consuming tab in the background with the given strategy
# Options: rss_limit, background_time_limit, cpu_idle_time
kill_tab_strategies = ["rss_limit"]

# Check interval of choosen strategy
# Range: 0.0 ~ inf
check_interval_secs = 1.0

# A list of regex, tab will not be kill if matche any
# Example: whitelist: ["https://docs.rs"]
whitelist = []

# Kill the tab if all tabs total resident set size (physical memory usage) hit limit, kill in descending order
[strategy.rss_limit]
# Range: 0 ~ 18_446_744_073_709_551_615
max_bytes = 2_000_000_000

# Kill the tab if it is in background for too long, this will not kill "New Tab"
[strategy.background_time_limit]
# Range: 0.0 ~ inf
max_secs = 86400.0

# Kill the tab if it have not use cpu for too long
# 🚧 Not implemented
[strategy.cpu_idle_time]
# Range: 0.0 ~ inf
max_secs = 86400.0
